// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getRowCount.proto

package hbase.coprocessor;

public final class getRowCount {
  private getRowCount() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface getRowCountRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:getRowCountRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool reCount = 1;</code>
     */
    boolean hasReCount();
    /**
     * <code>required bool reCount = 1;</code>
     */
    boolean getReCount();
  }
  /**
   * Protobuf type {@code getRowCountRequest}
   */
  public  static final class getRowCountRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:getRowCountRequest)
      getRowCountRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getRowCountRequest.newBuilder() to construct.
    private getRowCountRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getRowCountRequest() {
      reCount_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getRowCountRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              reCount_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ibm.developerworks.getRowCount.internal_static_getRowCountRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ibm.developerworks.getRowCount.internal_static_getRowCountRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ibm.developerworks.getRowCount.getRowCountRequest.class, org.ibm.developerworks.getRowCount.getRowCountRequest.Builder.class);
    }

    private int bitField0_;
    public static final int RECOUNT_FIELD_NUMBER = 1;
    private boolean reCount_;
    /**
     * <code>required bool reCount = 1;</code>
     */
    public boolean hasReCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool reCount = 1;</code>
     */
    public boolean getReCount() {
      return reCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasReCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, reCount_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, reCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ibm.developerworks.getRowCount.getRowCountRequest)) {
        return super.equals(obj);
      }
      org.ibm.developerworks.getRowCount.getRowCountRequest other = (org.ibm.developerworks.getRowCount.getRowCountRequest) obj;

      boolean result = true;
      result = result && (hasReCount() == other.hasReCount());
      if (hasReCount()) {
        result = result && (getReCount()
            == other.getReCount());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReCount()) {
        hash = (37 * hash) + RECOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getReCount());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ibm.developerworks.getRowCount.getRowCountRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getRowCountRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:getRowCountRequest)
        org.ibm.developerworks.getRowCount.getRowCountRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ibm.developerworks.getRowCount.internal_static_getRowCountRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ibm.developerworks.getRowCount.internal_static_getRowCountRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ibm.developerworks.getRowCount.getRowCountRequest.class, org.ibm.developerworks.getRowCount.getRowCountRequest.Builder.class);
      }

      // Construct using org.ibm.developerworks.getRowCount.getRowCountRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        reCount_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ibm.developerworks.getRowCount.internal_static_getRowCountRequest_descriptor;
      }

      public org.ibm.developerworks.getRowCount.getRowCountRequest getDefaultInstanceForType() {
        return org.ibm.developerworks.getRowCount.getRowCountRequest.getDefaultInstance();
      }

      public org.ibm.developerworks.getRowCount.getRowCountRequest build() {
        org.ibm.developerworks.getRowCount.getRowCountRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.ibm.developerworks.getRowCount.getRowCountRequest buildPartial() {
        org.ibm.developerworks.getRowCount.getRowCountRequest result = new org.ibm.developerworks.getRowCount.getRowCountRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reCount_ = reCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ibm.developerworks.getRowCount.getRowCountRequest) {
          return mergeFrom((org.ibm.developerworks.getRowCount.getRowCountRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ibm.developerworks.getRowCount.getRowCountRequest other) {
        if (other == org.ibm.developerworks.getRowCount.getRowCountRequest.getDefaultInstance()) return this;
        if (other.hasReCount()) {
          setReCount(other.getReCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReCount()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.ibm.developerworks.getRowCount.getRowCountRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.ibm.developerworks.getRowCount.getRowCountRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean reCount_ ;
      /**
       * <code>required bool reCount = 1;</code>
       */
      public boolean hasReCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool reCount = 1;</code>
       */
      public boolean getReCount() {
        return reCount_;
      }
      /**
       * <code>required bool reCount = 1;</code>
       */
      public Builder setReCount(boolean value) {
        bitField0_ |= 0x00000001;
        reCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool reCount = 1;</code>
       */
      public Builder clearReCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reCount_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:getRowCountRequest)
    }

    // @@protoc_insertion_point(class_scope:getRowCountRequest)
    private static final org.ibm.developerworks.getRowCount.getRowCountRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ibm.developerworks.getRowCount.getRowCountRequest();
    }

    public static org.ibm.developerworks.getRowCount.getRowCountRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<getRowCountRequest>
        PARSER = new com.google.protobuf.AbstractParser<getRowCountRequest>() {
      public getRowCountRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getRowCountRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getRowCountRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<getRowCountRequest> getParserForType() {
      return PARSER;
    }

    public org.ibm.developerworks.getRowCount.getRowCountRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface getRowCountResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:getRowCountResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 rowCount = 1;</code>
     */
    boolean hasRowCount();
    /**
     * <code>optional int64 rowCount = 1;</code>
     */
    long getRowCount();
  }
  /**
   * Protobuf type {@code getRowCountResponse}
   */
  public  static final class getRowCountResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:getRowCountResponse)
      getRowCountResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getRowCountResponse.newBuilder() to construct.
    private getRowCountResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getRowCountResponse() {
      rowCount_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getRowCountResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rowCount_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ibm.developerworks.getRowCount.internal_static_getRowCountResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ibm.developerworks.getRowCount.internal_static_getRowCountResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ibm.developerworks.getRowCount.getRowCountResponse.class, org.ibm.developerworks.getRowCount.getRowCountResponse.Builder.class);
    }

    private int bitField0_;
    public static final int ROWCOUNT_FIELD_NUMBER = 1;
    private long rowCount_;
    /**
     * <code>optional int64 rowCount = 1;</code>
     */
    public boolean hasRowCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 rowCount = 1;</code>
     */
    public long getRowCount() {
      return rowCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rowCount_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rowCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ibm.developerworks.getRowCount.getRowCountResponse)) {
        return super.equals(obj);
      }
      org.ibm.developerworks.getRowCount.getRowCountResponse other = (org.ibm.developerworks.getRowCount.getRowCountResponse) obj;

      boolean result = true;
      result = result && (hasRowCount() == other.hasRowCount());
      if (hasRowCount()) {
        result = result && (getRowCount()
            == other.getRowCount());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRowCount()) {
        hash = (37 * hash) + ROWCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRowCount());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ibm.developerworks.getRowCount.getRowCountResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ibm.developerworks.getRowCount.getRowCountResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getRowCountResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:getRowCountResponse)
        org.ibm.developerworks.getRowCount.getRowCountResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ibm.developerworks.getRowCount.internal_static_getRowCountResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ibm.developerworks.getRowCount.internal_static_getRowCountResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ibm.developerworks.getRowCount.getRowCountResponse.class, org.ibm.developerworks.getRowCount.getRowCountResponse.Builder.class);
      }

      // Construct using org.ibm.developerworks.getRowCount.getRowCountResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rowCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ibm.developerworks.getRowCount.internal_static_getRowCountResponse_descriptor;
      }

      public org.ibm.developerworks.getRowCount.getRowCountResponse getDefaultInstanceForType() {
        return org.ibm.developerworks.getRowCount.getRowCountResponse.getDefaultInstance();
      }

      public org.ibm.developerworks.getRowCount.getRowCountResponse build() {
        org.ibm.developerworks.getRowCount.getRowCountResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.ibm.developerworks.getRowCount.getRowCountResponse buildPartial() {
        org.ibm.developerworks.getRowCount.getRowCountResponse result = new org.ibm.developerworks.getRowCount.getRowCountResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowCount_ = rowCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ibm.developerworks.getRowCount.getRowCountResponse) {
          return mergeFrom((org.ibm.developerworks.getRowCount.getRowCountResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ibm.developerworks.getRowCount.getRowCountResponse other) {
        if (other == org.ibm.developerworks.getRowCount.getRowCountResponse.getDefaultInstance()) return this;
        if (other.hasRowCount()) {
          setRowCount(other.getRowCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.ibm.developerworks.getRowCount.getRowCountResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.ibm.developerworks.getRowCount.getRowCountResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long rowCount_ ;
      /**
       * <code>optional int64 rowCount = 1;</code>
       */
      public boolean hasRowCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 rowCount = 1;</code>
       */
      public long getRowCount() {
        return rowCount_;
      }
      /**
       * <code>optional int64 rowCount = 1;</code>
       */
      public Builder setRowCount(long value) {
        bitField0_ |= 0x00000001;
        rowCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 rowCount = 1;</code>
       */
      public Builder clearRowCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowCount_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:getRowCountResponse)
    }

    // @@protoc_insertion_point(class_scope:getRowCountResponse)
    private static final org.ibm.developerworks.getRowCount.getRowCountResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ibm.developerworks.getRowCount.getRowCountResponse();
    }

    public static org.ibm.developerworks.getRowCount.getRowCountResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<getRowCountResponse>
        PARSER = new com.google.protobuf.AbstractParser<getRowCountResponse>() {
      public getRowCountResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getRowCountResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getRowCountResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<getRowCountResponse> getParserForType() {
      return PARSER;
    }

    public org.ibm.developerworks.getRowCount.getRowCountResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code ibmDeveloperWorksService}
   */
  public static abstract class ibmDeveloperWorksService
      implements com.google.protobuf.Service {
    protected ibmDeveloperWorksService() {}

    public interface Interface {
      /**
       * <code>rpc getRowCount(.getRowCountRequest) returns (.getRowCountResponse);</code>
       */
      public abstract void getRowCount(
              com.google.protobuf.RpcController controller,
              org.ibm.developerworks.getRowCount.getRowCountRequest request,
              com.google.protobuf.RpcCallback<org.ibm.developerworks.getRowCount.getRowCountResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new ibmDeveloperWorksService() {
        @Override
        public  void getRowCount(
            com.google.protobuf.RpcController controller,
            org.ibm.developerworks.getRowCount.getRowCountRequest request,
            com.google.protobuf.RpcCallback<org.ibm.developerworks.getRowCount.getRowCountResponse> done) {
          impl.getRowCount(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getRowCount(controller, (org.ibm.developerworks.getRowCount.getRowCountRequest)request);
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.ibm.developerworks.getRowCount.getRowCountRequest.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.ibm.developerworks.getRowCount.getRowCountResponse.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getRowCount(.getRowCountRequest) returns (.getRowCountResponse);</code>
     */
    public abstract void getRowCount(
        com.google.protobuf.RpcController controller,
        org.ibm.developerworks.getRowCount.getRowCountRequest request,
        com.google.protobuf.RpcCallback<org.ibm.developerworks.getRowCount.getRowCountResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.ibm.developerworks.getRowCount.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getRowCount(controller, (org.ibm.developerworks.getRowCount.getRowCountRequest)request,
            com.google.protobuf.RpcUtil.<org.ibm.developerworks.getRowCount.getRowCountResponse>specializeCallback(
              done));
          return;
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.ibm.developerworks.getRowCount.getRowCountRequest.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.ibm.developerworks.getRowCount.getRowCountResponse.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.ibm.developerworks.getRowCount.ibmDeveloperWorksService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getRowCount(
          com.google.protobuf.RpcController controller,
          org.ibm.developerworks.getRowCount.getRowCountRequest request,
          com.google.protobuf.RpcCallback<org.ibm.developerworks.getRowCount.getRowCountResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.ibm.developerworks.getRowCount.getRowCountResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.ibm.developerworks.getRowCount.getRowCountResponse.class,
            org.ibm.developerworks.getRowCount.getRowCountResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.ibm.developerworks.getRowCount.getRowCountResponse getRowCount(
              com.google.protobuf.RpcController controller,
              org.ibm.developerworks.getRowCount.getRowCountRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.ibm.developerworks.getRowCount.getRowCountResponse getRowCount(
          com.google.protobuf.RpcController controller,
          org.ibm.developerworks.getRowCount.getRowCountRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.ibm.developerworks.getRowCount.getRowCountResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.ibm.developerworks.getRowCount.getRowCountResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:ibmDeveloperWorksService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getRowCountRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getRowCountRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getRowCountResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getRowCountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021getRowCount.proto\"%\n\022getRowCountReques" +
      "t\022\017\n\007reCount\030\001 \002(\010\"\'\n\023getRowCountRespons" +
      "e\022\020\n\010rowCount\030\001 \001(\0032T\n\030ibmDeveloperWorks" +
      "Service\0228\n\013getRowCount\022\023.getRowCountRequ" +
      "est\032\024.getRowCountResponseB*\n\026org.ibm.dev" +
      "eloperworksB\013getRowCountH\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_getRowCountRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_getRowCountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getRowCountRequest_descriptor,
        new String[] { "ReCount", });
    internal_static_getRowCountResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_getRowCountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getRowCountResponse_descriptor,
        new String[] { "RowCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
